---

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  jest: true

extends:
  - 'airbnb-base'
  - plugin:import/errors
- plugin:import/warnings

rules:
  no-console: 0


